### ISSUE TITLE
Look at existing libraries

### ISSUE THREAD

**Issue by colinli02** [UBCSailbot/custom_interfaces#3]
### Purpose
To look at existing ROS libraries that could be used.

### Changes

Possibly use existing ROS libraries to improve on current libraries.

### Resources

- https://github.com/ros2/common_interfaces/tree/humble
- https://github.com/UBCSailbot/custom_interfaces/pull/2#issuecomment-1577866615

**Comment by colinli02** [comment]
I will update this as I go:
https://github.com/ros2/common_interfaces  branch ```rolling``` (default)
I have ignored what is already defined in [\custom_interfaces](https://github.com/UBCSailbot/custom_interfaces) (e.g. Vector3)
## Likely Useful ✔️
| Package Name | Message Name(s) | Justification  |
| -------------      | -------------      | -------------   |
| geometry_msgs | Accel, AccelStamped | Very common basic messages
| nav_msgs | ALL  | CTRL / PATH?  |
| sensor_msgs  | BatteryState  | Detailed battery information. Not sure of extent of how we can track battery  |
| sensor_msgs  | NavSatFix, NavSatStatus | Some navigation, maybe for PATH?  |
## Possibly useful
| Package Name | Message Name(s) | Justification  |
| -------------      | -------------      | -------------   |
| sensor_msgs  | TimeReference  | Storage of time |
| geometry_msgs | AccelWithCovariance, AccelWithCovarianceStamped, Inertia, Inertiastamped, Point, Point32| Might be useful for CTRL? Some more advanced physics msgs |
| std_msgs| ALL  | Every single data type possible (I think). Could be useful as reference if people have trouble  |
| sensor_msgs| RelativeHumidity, Temperature  | Temperature stuff. I recall ELEC mentioning temperature sensors? Unclear |
| visualization_msgs | ALL  | Will simulator want to use ROS for storing visual stuff? If then possibly useful  |
## Likely not useful
| Package Name | Message Name(s) | Justification  |
| -------------      | -------------      | -------------   |
| geometry_msgs | Pose, Pose2D, PoseArray, PoseStamped, PoseWithCovariance, Quaternion, Transform  | Some free space x y z stuff. Not sure if too concerned about y axis on boat  |
| std_srvs| ALL  | Empty srv templates. If we use .srv, could be useful to look at. |
| shape_msgs| ALL  |  Describes common shapes and shape data (e.g. cylinder radius) |
| actionlib_msgs | ALL  | Messages for "goals" & status. Don't think it's relevant unless we want 'goals' of boat at midpoint and its status updates on it. |
## Likely Irrelevant ❌
| Package Name | Message Name(s) | Justification  |
| -------------      | -------------      | -------------   |
| diagnostic_msgs | ALL  | Don't think we are tracking hardware status or have relevant sensors  |
| joint_msgs | ALL  | Messages for robot / general joint movement.   | Don't think we are controlling any joint pos / velocities, etc
| stereo_msgs| ALL  | This is for camera data (focal lengths, etc.)|
| sensor_msgs  | CameraInfo, ChannelFloat, CompressedImage, FluidPressure, Illuminance, Imu, JointState, Joy, JoyFeedBack, JoyFeedbackArray, LaserEcho, LaserScan, MagneticField, MultiDOFJointState, MultiEchoLaserScan, Range, RegionOfInterest| Don't think we have sensors / within our scope. Mostly camera stuff  |
| sensor_msgs| PointCloud, PointCloud2, PointField  | PointCloud2 message entry format, "depreciated as of foxy"|

**Comment by patrick-5546** [comment]
Great summary of the msgs available, the tables make it really easy to understand.

A couple of comments:
- Shouldn't make a big different, but should look at the `humble` branch, as this is the ROS version that Sailbot Workspace uses
- `Vector3.msg` isn't defined in custom_interfaces

My high level takeaways of common_interfaces:
- We don't have to use these messages for everything
    - our msgs should only contain the fields we need
    - Fields should be commented with any particular things of note (conventions, units)
    - Still could be useful as a reference
- I think we shouldn't put the units in the field name
- Can define enums in the message (didn't even know you could do that)

Going through each of the packages myself:
- actionlib: irrelevant (exists to support bridging ROS 1 action topics)
- diagnostic: could be used to display status of sensors on website
- geometry: could be used in simulator and local pathfinding (predicted boat positions)
- nav: not directly useful, but I like the idea of using getter services for longer running tasks; for example, when we get the global path from satellite we can use a service to update it in local pathfinding
- sensor: again not directly useful, but good reference for CAN transceiver; for example, BatteryState
- shape: can't think why we would need these
- std_msgs: besides all the types it defines, empty and header seem cool
    - Can't think of a potential use for use for empty rn, but it's something that I haven't thought of before so worth a mention
    - header would be helpful for debugging and uniquely identifying an element in a array; for example, header for AISShip could be timestamp and AIS ID
- std_srvs: all I could see being useful
- stereo: irrelevant
- trajectory: irrelevant
- visualization: potentially useful reference

What's next:
- Discuss whether to create issue to remove fields that end with units like `_degrees` or `_kmph` and instead comment this
- Create issues for other things as desired
- Add section in README documenting the common_interfaces repo
